### ISSUE TITLE
Update for version 75

### ISSUE THREAD

**Issue by haniag** [insanj/SaveGram#24]
I am on version 75, and one thing that has changed is this method

    -(void)handleActionSheetDismissedWithButtonTitled:(NSString *)arg1 forFeedItem:(IGFeedItem *)arg2 navigationController:(id)arg3 sourceName:(id)arg4 position:(unsigned long long)arg5

to

    -(void)handleActionSheetDismissedWithButtonTitled:(id)buttonTitled forFeedItem:(IGFeedItem *)item navigationController:(id)arg3 source:(id)arg4 sourceName:(id)arg5 position:(id)arg6 supportSponsoredTracking:(id)arg7{

However, the images/videos are not saving, and the app is stuck on "Saving..." Fix for whatever is causing this would probably apply to future versions.

**Comment by insanj** [comment]
Thanks for reporting this issue. I haven't had the opportunity to test my tweaks on the latest jailbreak in a long time, but I'll do my best to investigate this once I can. 👍

**Comment by haniag** [comment]
I have found out an issue: "imageVersions" array is no longer available. Hence, the image doesn't save as URL is not found. It seems an alternative is the "_processedImageVersions" array, also found in "IGPhoto". However, this is an ivar and I get the error message:

    instance variable '_processedImageVersions' is protected

with this code:

    NSURL *imageURL = savegram_highestResolutionURLFromVersionArray(postItem.photo->_processedImageVersions);

The header file has:

    @interface IGPhoto : NSObject  {
        NSArray *_processedImageVersions;
    }
    - (id)imageURLForSize:(CGSize)size;
    @end

IDA doesn't show a property defined for "_processedImageVersions", and if I define one in header, then I get in log:

    -[IGPhoto processedImageVersions]: unrecognized selector sent to instance 0x1c4c76980

Hence, can you please advise how to access this ivar to get the URL lists? Thanks.

**Comment by haniag** [comment]
The solution is to access the array while in the IGMediaManager method:

    NSArray *myArray = MSHookIvar<NSArray *>(item.photo, "_processedImageVersions");

and then call the save function with that extra parameter, without the need for index:

    savegram_saveMediaFromFeedItem(item, myArray);

where the highest resoltion method will just receive the ready array:

    NSURL *imageURL = savegram_highestResolutionURLFromVersionArray(versionArray);

This is only the case for images and stories, where for video, videoVersions array remains accessible via its property. Also, this carries along to latest IG version 106.
